spring:
  cloud:
    config:
      label: master
      profile: dev
      name: modules-admin, mysql, redis
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
