eureka:
  client:
    #服务注册开关
    registerWithEureka: true
    #服务发现开关
    fetchRegistry: true
    #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULTZONE}
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    # 将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true
  # 请求处理的超时时间
  ReadTimeout: 60000
  # 请求连接的超时时间
  ConnectTimeout: 60000
  # 最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetries: 2
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 3
  # 对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  OkToRetryOnAllOperations: false


hystrix:
  threadpool:
    default:
      # 并发执行的最大线程数，默认10
      coreSize: 10
      # BlockingQueue的最大队列数
      maxQueueSize: 10
      # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      queueSizeRejectionThreshold: 10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
