MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_USERNAME: root
MYSQL_PASSWORD: 1111

EUREKA_HOST: 127.0.0.1
EUREKA_PORT: 8761

REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_PWD:

EUREKA_DEFAULTZONE: http://127.0.0.1:8761/eureka/
