spring:
    application:
        name: gateway-zuul
server:
  port: 9999

zuul:
  routes:
    api-a:
      path: /admin/**
      # 如果是/ribbon/**路径下的请求，则跳转到service-ribbon
      serviceId: admin
    api-b:
      path: /feign/**
      # 如果是/feign/**路径下的请求，则跳转到service-feign
      serviceId: service-feign