server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/szmiao/springcloud.git
          search-paths: config
          username: ENC(H0uY0jT/oB0ZCbVzOGUI5Q==)
          password: ENC(QPaOXMPdPMlW3NukGKH9JrjlN+WJP+ry)

jasypt:
  encryptor:
    password: msz
